language: node_js
node_js:
  - "6"
services:
  - mongodb
after_script:
  - npm run codeclimate
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    rooms:
      gorlifsense:S7RWHqp3eUYiYBusZOzXytvR#development
    on_success: change
